// Auto-generated. Do not edit!

// (in-package armaction.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ArmControlFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_joints = null;
      this.progress = null;
      this.state = null;
    }
    else {
      if (initObj.hasOwnProperty('current_joints')) {
        this.current_joints = initObj.current_joints
      }
      else {
        this.current_joints = [];
      }
      if (initObj.hasOwnProperty('progress')) {
        this.progress = initObj.progress
      }
      else {
        this.progress = 0.0;
      }
      if (initObj.hasOwnProperty('state')) {
        this.state = initObj.state
      }
      else {
        this.state = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ArmControlFeedback
    // Serialize message field [current_joints]
    bufferOffset = _arraySerializer.float32(obj.current_joints, buffer, bufferOffset, null);
    // Serialize message field [progress]
    bufferOffset = _serializer.float32(obj.progress, buffer, bufferOffset);
    // Serialize message field [state]
    bufferOffset = _serializer.string(obj.state, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ArmControlFeedback
    let len;
    let data = new ArmControlFeedback(null);
    // Deserialize message field [current_joints]
    data.current_joints = _arrayDeserializer.float32(buffer, bufferOffset, null)
    // Deserialize message field [progress]
    data.progress = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [state]
    data.state = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 4 * object.current_joints.length;
    length += _getByteLength(object.state);
    return length + 12;
  }

  static datatype() {
    // Returns string type for a message object
    return 'armaction/ArmControlFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'f7cc27d8325ec06677f29e18067f057c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    float32[] current_joints 
    float32 progress        
    string state            
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ArmControlFeedback(null);
    if (msg.current_joints !== undefined) {
      resolved.current_joints = msg.current_joints;
    }
    else {
      resolved.current_joints = []
    }

    if (msg.progress !== undefined) {
      resolved.progress = msg.progress;
    }
    else {
      resolved.progress = 0.0
    }

    if (msg.state !== undefined) {
      resolved.state = msg.state;
    }
    else {
      resolved.state = ''
    }

    return resolved;
    }
};

module.exports = ArmControlFeedback;
