(cl:defpackage armaction-msg
  (:use )
  (:export
   "<ARMCONTROLACTION>"
   "ARMCONTROLACTION"
   "<ARMCONTROLACTIONFEEDBACK>"
   "ARMCONTROLACTIONFEEDBACK"
   "<ARMCONTROLACTIONGOAL>"
   "ARMCONTROLACTIONGOAL"
   "<ARMCONTROLACTIONRESULT>"
   "ARMCONTROLACTIONRESULT"
   "<ARMCONTROLFEEDBACK>"
   "ARMCONTROLFEEDBACK"
   "<ARMCONTROLGOAL>"
   "ARMCONTROLGOAL"
   "<ARMCONTROLRESULT>"
   "ARMCONTROLRESULT"
  ))

