// Generated by gencpp from file armaction/ArmControlResult.msg
// DO NOT EDIT!


#ifndef ARMACTION_MESSAGE_ARMCONTROLRESULT_H
#define ARMACTION_MESSAGE_ARMCONTROLRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace armaction
{
template <class ContainerAllocator>
struct ArmControlResult_
{
  typedef ArmControlResult_<ContainerAllocator> Type;

  ArmControlResult_()
    : success(false)
    , message()  {
    }
  ArmControlResult_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::armaction::ArmControlResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::armaction::ArmControlResult_<ContainerAllocator> const> ConstPtr;

}; // struct ArmControlResult_

typedef ::armaction::ArmControlResult_<std::allocator<void> > ArmControlResult;

typedef boost::shared_ptr< ::armaction::ArmControlResult > ArmControlResultPtr;
typedef boost::shared_ptr< ::armaction::ArmControlResult const> ArmControlResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::armaction::ArmControlResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::armaction::ArmControlResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::armaction::ArmControlResult_<ContainerAllocator1> & lhs, const ::armaction::ArmControlResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::armaction::ArmControlResult_<ContainerAllocator1> & lhs, const ::armaction::ArmControlResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace armaction

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::armaction::ArmControlResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::armaction::ArmControlResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::armaction::ArmControlResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::armaction::ArmControlResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::armaction::ArmControlResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::armaction::ArmControlResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::armaction::ArmControlResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::armaction::ArmControlResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::armaction::ArmControlResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "armaction/ArmControlResult";
  }

  static const char* value(const ::armaction::ArmControlResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::armaction::ArmControlResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"bool success             \n"
"string message          \n"
"\n"
;
  }

  static const char* value(const ::armaction::ArmControlResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::armaction::ArmControlResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmControlResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::armaction::ArmControlResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::armaction::ArmControlResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARMACTION_MESSAGE_ARMCONTROLRESULT_H
