// Generated by gencpp from file armaction/ArmControlGoal.msg
// DO NOT EDIT!


#ifndef ARMACTION_MESSAGE_ARMCONTROLGOAL_H
#define ARMACTION_MESSAGE_ARMCONTROLGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace armaction
{
template <class ContainerAllocator>
struct ArmControlGoal_
{
  typedef ArmControlGoal_<ContainerAllocator> Type;

  ArmControlGoal_()
    : target_joints()
    , duration(0.0)
    , speed(0.0)  {
    }
  ArmControlGoal_(const ContainerAllocator& _alloc)
    : target_joints(_alloc)
    , duration(0.0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _target_joints_type;
  _target_joints_type target_joints;

   typedef float _duration_type;
  _duration_type duration;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::armaction::ArmControlGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::armaction::ArmControlGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ArmControlGoal_

typedef ::armaction::ArmControlGoal_<std::allocator<void> > ArmControlGoal;

typedef boost::shared_ptr< ::armaction::ArmControlGoal > ArmControlGoalPtr;
typedef boost::shared_ptr< ::armaction::ArmControlGoal const> ArmControlGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::armaction::ArmControlGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::armaction::ArmControlGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::armaction::ArmControlGoal_<ContainerAllocator1> & lhs, const ::armaction::ArmControlGoal_<ContainerAllocator2> & rhs)
{
  return lhs.target_joints == rhs.target_joints &&
    lhs.duration == rhs.duration &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::armaction::ArmControlGoal_<ContainerAllocator1> & lhs, const ::armaction::ArmControlGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace armaction

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::armaction::ArmControlGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::armaction::ArmControlGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::armaction::ArmControlGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::armaction::ArmControlGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::armaction::ArmControlGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::armaction::ArmControlGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::armaction::ArmControlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10fd138217332a6be1290c5c92c60103";
  }

  static const char* value(const ::armaction::ArmControlGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10fd138217332a6bULL;
  static const uint64_t static_value2 = 0xe1290c5c92c60103ULL;
};

template<class ContainerAllocator>
struct DataType< ::armaction::ArmControlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "armaction/ArmControlGoal";
  }

  static const char* value(const ::armaction::ArmControlGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::armaction::ArmControlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"float32[] target_joints  \n"
"float32 duration        \n"
"float32 speed           \n"
"\n"
;
  }

  static const char* value(const ::armaction::ArmControlGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::armaction::ArmControlGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_joints);
      stream.next(m.duration);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmControlGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::armaction::ArmControlGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::armaction::ArmControlGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "target_joints: ";
    if (v.target_joints.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.target_joints.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.target_joints[i]);
    }
    if (v.target_joints.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "duration: ";
    Printer<float>::stream(s, indent + "  ", v.duration);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARMACTION_MESSAGE_ARMCONTROLGOAL_H
