// Generated by gencpp from file armaction/ArmControlFeedback.msg
// DO NOT EDIT!


#ifndef ARMACTION_MESSAGE_ARMCONTROLFEEDBACK_H
#define ARMACTION_MESSAGE_ARMCONTROLFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace armaction
{
template <class ContainerAllocator>
struct ArmControlFeedback_
{
  typedef ArmControlFeedback_<ContainerAllocator> Type;

  ArmControlFeedback_()
    : current_joints()
    , progress(0.0)
    , state()  {
    }
  ArmControlFeedback_(const ContainerAllocator& _alloc)
    : current_joints(_alloc)
    , progress(0.0)
    , state(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _current_joints_type;
  _current_joints_type current_joints;

   typedef float _progress_type;
  _progress_type progress;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::armaction::ArmControlFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::armaction::ArmControlFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ArmControlFeedback_

typedef ::armaction::ArmControlFeedback_<std::allocator<void> > ArmControlFeedback;

typedef boost::shared_ptr< ::armaction::ArmControlFeedback > ArmControlFeedbackPtr;
typedef boost::shared_ptr< ::armaction::ArmControlFeedback const> ArmControlFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::armaction::ArmControlFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::armaction::ArmControlFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::armaction::ArmControlFeedback_<ContainerAllocator1> & lhs, const ::armaction::ArmControlFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.current_joints == rhs.current_joints &&
    lhs.progress == rhs.progress &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::armaction::ArmControlFeedback_<ContainerAllocator1> & lhs, const ::armaction::ArmControlFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace armaction

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::armaction::ArmControlFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::armaction::ArmControlFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::armaction::ArmControlFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::armaction::ArmControlFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::armaction::ArmControlFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::armaction::ArmControlFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::armaction::ArmControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7cc27d8325ec06677f29e18067f057c";
  }

  static const char* value(const ::armaction::ArmControlFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7cc27d8325ec066ULL;
  static const uint64_t static_value2 = 0x77f29e18067f057cULL;
};

template<class ContainerAllocator>
struct DataType< ::armaction::ArmControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "armaction/ArmControlFeedback";
  }

  static const char* value(const ::armaction::ArmControlFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::armaction::ArmControlFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"float32[] current_joints \n"
"float32 progress        \n"
"string state            \n"
"\n"
;
  }

  static const char* value(const ::armaction::ArmControlFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::armaction::ArmControlFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_joints);
      stream.next(m.progress);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmControlFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::armaction::ArmControlFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::armaction::ArmControlFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "current_joints: ";
    if (v.current_joints.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.current_joints.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.current_joints[i]);
    }
    if (v.current_joints.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "progress: ";
    Printer<float>::stream(s, indent + "  ", v.progress);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARMACTION_MESSAGE_ARMCONTROLFEEDBACK_H
